### ISSUE TITLE
track go/issues/40221 : detached context

### ISSUE THREAD

**Issue by komuw** [komuw/ong#110]
https://github.com/golang/go/issues/40221

**Comment by komuw** [comment]
If that proposal is accepted, remove the xcontext package; https://github.com/komuw/ong/pull/109

**Comment by komuw** [comment]
Add semgrep rule for it;
```
rules:
  - id: http-request-go-context
    patterns:
    - pattern: |
        $CTX := ($R : *http.Request).Context()
        ...
        go $F($CTX, ...)
    message: "passing an http-request scoped Context to a goroutine"
    languages: [go]
    severity: ERROR
```

from; https://gophers.slack.com/archives/C0VP8EF3R/p1662499682124379?thread_ts=1662488784.325789&cid=C0VP8EF3R
